[Main]
GCM_WhiteList_Path=c:\OEM\preload\DPOP\GCMReadiness\IM_WhiteList.txt
;GCM white list: to record a white list for IM

Reboot_Timeout=6
;Reboot timeout: countdown seconds for rebooting

SWOD_Launch_Mode=False
;Default is False. It will be set to True if AlaunchX is launched by SWOD